-- MySQL Script generated by MySQL Workbench
-- Mon 21 Mar 2022 14:51:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema group_12_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema group_12_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `group_12_database` ;
USE `group_12_database` ;

-- -----------------------------------------------------
-- Table `group_12_database`.`Companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`Companies` (
  `CompanyID` INT NOT NULL,
  `CompanyName` VARCHAR(63) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `GeneralIndustry` VARCHAR(255) NOT NULL,
  `CompanyAddress` VARCHAR(100) NOT NULL,
  `YearEstablished` INT NOT NULL,
  `CompanyEmail` VARCHAR(100) NOT NULL,
  `CompanyPhone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CompanyID`),
  UNIQUE INDEX `CompanyName_UNIQUE` (`CompanyName` ASC) VISIBLE,
  UNIQUE INDEX `CompanyID_UNIQUE` (`CompanyID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`Developers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`Developers` (
  `DeveloperID` INT NOT NULL,
  `DeveloperEmail` VARCHAR(127) NOT NULL,
  `Password` VARCHAR(512) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DOB` DATETIME NOT NULL,
  `Country` VARCHAR(60) NOT NULL,
  `Description` VARCHAR(3000) NOT NULL,
  UNIQUE INDEX `DeveloperEmail_UNIQUE` (`DeveloperEmail` ASC) VISIBLE,
  PRIMARY KEY (`DeveloperID`),
  UNIQUE INDEX `DeveloperID_UNIQUE` (`DeveloperID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`BlockedCompanyInterface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`BlockedCompanyInterface` (
  `BlockID` INT NOT NULL,
  `CompanyID` INT NOT NULL,
  `DeveloperID` INT NOT NULL,
  PRIMARY KEY (`BlockID`),
  UNIQUE INDEX `BlockID_UNIQUE` (`BlockID` ASC) VISIBLE,
  INDEX `fk_BlockedCompanyInterface_Developers1_idx` (`DeveloperID` ASC) VISIBLE,
  INDEX `fk_BlockedCompanyInterface_Companies1_idx` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_BlockedCompanyInterface_Developers1`
    FOREIGN KEY (`DeveloperID`)
    REFERENCES `group_12_database`.`Developers` (`DeveloperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BlockedCompanyInterface_Companies1`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `group_12_database`.`Companies` (`CompanyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`ProgrammingLanguages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`ProgrammingLanguages` (
  `LanguageID` INT NOT NULL,
  `Language` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`LanguageID`),
  UNIQUE INDEX `LanguageID_UNIQUE` (`LanguageID` ASC) VISIBLE,
  UNIQUE INDEX `Language_UNIQUE` (`Language` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`Contracts` (
  `ContractID` INT NOT NULL,
  `CompanyID` INT NOT NULL,
  `ContractLength` INT NOT NULL,
  `ContractValue` DOUBLE NOT NULL,
  `ContractDescription` VARCHAR(300) NOT NULL,
  `InOffice` TINYINT NOT NULL,
  `DateIssued` DATE NOT NULL,
  `Open` TINYINT NOT NULL,
  `OfficeAddress` VARCHAR(100) NOT NULL,
  `ContractName` VARCHAR(50) NOT NULL,
  `DeveloperID` INT NOT NULL,
  PRIMARY KEY (`ContractID`),
  UNIQUE INDEX `ContractID_UNIQUE` (`ContractID` ASC) VISIBLE,
  INDEX `fk_Contracts_Companies_idx` (`CompanyID` ASC) VISIBLE,
  CONSTRAINT `fk_Contracts_Companies`
    FOREIGN KEY (`CompanyID`)
    REFERENCES `group_12_database`.`Companies` (`CompanyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`LanguageDeveloperInterface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`LanguageDeveloperInterface` (
  `LinkID` INT NOT NULL,
  `LanguageID` INT NOT NULL,
  `DeveloperID` INT NOT NULL,
  PRIMARY KEY (`LinkID`),
  UNIQUE INDEX `LinkID_UNIQUE` (`LinkID` ASC) VISIBLE,
  INDEX `fk_LanguageDeveloperInterface_Developers1_idx` (`DeveloperID` ASC) VISIBLE,
  INDEX `fk_LanguageDeveloperInterface_ProgrammingLanguages1_idx` (`LanguageID` ASC) VISIBLE,
  CONSTRAINT `fk_LanguageDeveloperInterface_Developers1`
    FOREIGN KEY (`DeveloperID`)
    REFERENCES `group_12_database`.`Developers` (`DeveloperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LanguageDeveloperInterface_ProgrammingLanguages1`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `group_12_database`.`ProgrammingLanguages` (`LanguageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`LanguageContractInterface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`LanguageContractInterface` (
  `LinkID` INT NOT NULL,
  `LanguageID` INT NOT NULL,
  `ContractID` INT NOT NULL,
  PRIMARY KEY (`LinkID`),
  UNIQUE INDEX `LinkID_UNIQUE` (`LinkID` ASC) VISIBLE,
  INDEX `fk_LanguageContractInterface_ProgrammingLanguages1_idx` (`LanguageID` ASC) VISIBLE,
  INDEX `fk_LanguageContractInterface_Contracts1_idx` (`ContractID` ASC) VISIBLE,
  CONSTRAINT `fk_LanguageContractInterface_ProgrammingLanguages1`
    FOREIGN KEY (`LanguageID`)
    REFERENCES `group_12_database`.`ProgrammingLanguages` (`LanguageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LanguageContractInterface_Contracts1`
    FOREIGN KEY (`ContractID`)
    REFERENCES `group_12_database`.`Contracts` (`ContractID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_12_database`.`ApplicationsInterface`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_12_database`.`ApplicationsInterface` (
  `ApplicationID` INT NOT NULL,
  `DeveloperID` INT NOT NULL,
  `ContractID` INT NOT NULL,
  PRIMARY KEY (`ApplicationID`),
  UNIQUE INDEX `ApplicationID_UNIQUE` (`ApplicationID` ASC) VISIBLE,
  INDEX `fk_ApplicationsInterface_Developers1_idx` (`DeveloperID` ASC) VISIBLE,
  INDEX `fk_ApplicationsInterface_Contracts1_idx` (`ContractID` ASC) VISIBLE,
  CONSTRAINT `fk_ApplicationsInterface_Developers1`
    FOREIGN KEY (`DeveloperID`)
    REFERENCES `group_12_database`.`Developers` (`DeveloperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ApplicationsInterface_Contracts1`
    FOREIGN KEY (`ContractID`)
    REFERENCES `group_12_database`.`Contracts` (`ContractID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
